angular.module('Pundit2', [
    'ngResource', 'ngSanitize', 'ngAnimate', 'ngResize','ngCookies',
    'mgcrea.ngStrap', 'templates-main', 'angular-md5', 'angularMoment', 'datePicker',
    'Pundit2.Core',
    'Pundit2.Annomatic',
    'Pundit2.AnnotationSidebar',
    'Pundit2.AlertSystem',
    'Pundit2.Dashboard',
    'Pundit2.Model', 
    'Pundit2.Toolbar',
    'Pundit2.LiteTool',
    'Pundit2.Communication',
    'Pundit2.Annotators',
    'Pundit2.ContextualMenu',
    'Pundit2.AnnotationPopover',
    'Pundit2.FragmentPopover',
    'Pundit2.Preview',
    'Pundit2.Client',
    'Pundit2.GeneralItemsContainer',
    'Pundit2.PageItemsContainer',
    'Pundit2.Item',
    'Pundit2.MyItemsContainer',
    'Pundit2.ResourcePanel',
    'Pundit2.Vocabularies',
    'Pundit2.TripleComposer',
    'Pundit2.NotebookComposer',
    'Pundit2.VocabulariesContainer',
    'Pundit2.MyNotebooksContainer',
    'KorboEE',
    'Pundit2.SimplifiedClient',
    'Pundit2.PredicatesContainer',
    'Pundit2.Breadcrumbs',
    'yaru22.angular-timeago'
]);